name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KAKAO_CLIENT_ID: ${{ secrets.TEST_STRING_ENV }}
      KAKAO_CLIENT_SECRET: ${{ secrets.TEST_STRING_ENV }}
      KAKAO_REDIRECT_URI: ${{ secrets.TEST_STRING_ENV }}
      JWT_SECRET_KEY: ${{ secrets.TEST_JWT_KEY }}
      JWT_REFRESH_EXPIRE: ${{ secrets.TEST_INT_ENV }}
      JWT_ACCESS_EXPIRE: ${{ secrets.TEST_INT_ENV }}
      AWS_BUCKET_NAME: ${{ secrets.TEST_STRING_ENV }}
      AWS_ACCESS_KEY: ${{ secrets.TEST_STRING_ENV }}
      AWS_SECRET_KEY: ${{ secrets.TEST_STRING_ENV }}
      AWS_REGION: 'ap-northeast-2'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Publish artifacts
        if: success()
        run: |
          mkdir -p artifacts
          cp build/libs/*.jar artifacts/
