name: Build and Push Docker Image with Jib

on:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Copy application.yml from submodule
        run: |
          mkdir -p src/main/resources
          cp application-config/application-prod.yml src/main/resources/application-prod.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and push Docker image
        run: |
          ./gradlew jib -x test \
            -Djib.to.tags=${{ github.sha }} \
            -Djib.to.auth.username=${{ secrets.KAKAO_ACCESS_ID }} \
            -Djib.to.auth.password=${{ secrets.KAKAO_ACCESS_SECRET }}

  update-manifest-state:
    runs-on: self-hosted
    needs: build-and-push-image
    steps:
      - name: Checkout kic-k8s Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PROJECT }}/kic-k8s
          token: ${{ secrets.ACTIONS_TOKEN }}
          ref: "main"

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in deployment file
        run: |
          yq w -i clovider-app/be-deployment.yaml spec.template.spec.containers[0].image "kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:${{ github.sha }}"

      - name: Commit and Push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add clovider-app/be-deployment.yaml
          git commit -m "[skip ci] Update image tag to ${{ github.sha }}"
          git push
